### ISSUE TITLE
Multiple bugs/issues with http://www.day-planner.org/ php site

### ISSUE THREAD

**Issue by lod** [zerodogg/dayplanner#12]
Navigating the day-planner site shows lots of php errors.

There seem to be two groups of issues, some missing variables such as LangNum on the home page.

And php.ini has display_errors set to On. Changing this to Off on a production website is widely recommended as it improves security. It would also cause a large number of your display issues to immediately go away and make the remaining ones much harder to spot.

**Comment by zerodogg** [comment]
Fixed, thanks. Turned them on at some point to debug a problem with another site, looks like I forgot to turn them off again.
